import numpy as np

# --- Simulation ---
SIM_DT = 0.01

# --- PID tuning parameters (meters of suspension height offset output) ---
ROLL_SETPOINT = 0.0
PITCH_SETPOINT = 0.0
ROLL_KP = 0.05
ROLL_KI = 0.05
ROLL_KD = 0.05
PITCH_KP = 0.01
PITCH_KI = 0.00
PITCH_KD = 0.00

MAX_PID_Z_ADJUST = 0.05
MAX_LEG_DELTA_Z = 0.06

# --- Leg joint limits ---
HIP_ANGLE_MIN = -1.5
HIP_ANGLE_MAX = 1.5
KNEE_ANGLE_MIN = -2.5
KNEE_ANGLE_MAX = 0.0

NOMINAL_HIP_ANGLE = 0.785
NOMINAL_KNEE_ANGLE = -1.57
LEG_PREFIXES = ("fl", "fr", "rl", "rr")

# --- Suspension mixing ---
PITCH_MIX_SIGN_DEFAULT = 1.0
ROLL_MIX_SIGN_DEFAULT = -1.0
RESPAWN_SETTLE_STEPS = 20

# --- Viewer / command console ---
COMMAND_BUFFER_MAX = 96
COMMAND_HISTORY_MAX = 100

# --- Keyboard drive ---
KEYBOARD_VX_CMD = 24.0
KEYBOARD_YAW_CMD = -8.0

# --- Drive command gains ---
DRIVE_INPUT_VX_GAIN = 1.45
DRIVE_INPUT_OMEGA_GAIN = 1.10

# --- Ramp response gains ---
DRIVE_ACCEL_RESPONSE_GAIN = 1.80
DRIVE_BRAKE_RESPONSE_GAIN = 4
DRIVE_BRAKE_PREDICTIVE_GAIN = 1.20

# --- Rotate-only drift correction ---
ROTATE_ONLY_VX_DEADBAND = 0.15
ROTATE_ONLY_OMEGA_MIN = 0.10
ROTATE_DRIFT_KP = 24.0
ROTATE_DRIFT_KI = 6.0
ROTATE_DRIFT_KD = 3.0
ROTATE_DRIFT_I_LIMIT = 0.30
ROTATE_DRIFT_MAX_CORRECTION = 7.0

# --- Speed-adaptive drive envelope ---
DRIVE_POWER_SCALE_MIN = 2
DRIVE_POWER_SCALE_MAX = 5
DRIVE_OMEGA_SCALE_MAX = 2.40
DRIVE_POWER_SPEED_START_MPS = 0.10
DRIVE_POWER_SPEED_FULL_MPS = 1.80
DRIVE_POWER_YAW_START_RAD_S = float(np.deg2rad(12.0))
DRIVE_POWER_YAW_FULL_RAD_S = float(np.deg2rad(170.0))
DRIVE_VX_ACCEL_LIMIT_STATIONARY = 16.0
DRIVE_VX_ACCEL_LIMIT = 92.0
DRIVE_VX_DECEL_LIMIT_STATIONARY = 10
DRIVE_VX_DECEL_LIMIT = 150
DRIVE_BRAKE_THROTTLE_MIN = 0.5
DRIVE_BRAKE_REVERSE_SCALE = 0.65
DRIVE_BRAKE_PITCH_WARN_RAD = float(np.deg2rad(5.0))
DRIVE_BRAKE_PITCH_BLOCK_RAD = float(np.deg2rad(18.0))
DRIVE_BRAKE_PITCH_RATE_WARN_RAD_S = float(np.deg2rad(25.0))
DRIVE_BRAKE_PITCH_RATE_BLOCK_RAD_S = float(np.deg2rad(130.0))
DRIVE_STATE_FILTER_ALPHA = 0.25

# --- Traction control ---
TRACTION_NEUTRAL_SPEED_MPS = 0.15
TRACTION_NEUTRAL_CMD = 0.5
TRACTION_NEUTRAL_PITCH_ALPHA = 0.02
TRACTION_PITCH_WARN_RAD = float(np.deg2rad(7.0))
TRACTION_PITCH_BLOCK_RAD = float(np.deg2rad(14.0))
TRACTION_PITCH_RATE_WARN_RAD_S = float(np.deg2rad(40.0))
TRACTION_PITCH_RATE_BLOCK_RAD_S = float(np.deg2rad(130.0))
TRACTION_CMD_ACCEL_WARN = 10.0
TRACTION_CMD_ACCEL_BLOCK = 45.0
TRACTION_RISK_START = 0.35
TRACTION_RISK_HARD_BLOCK = 0.90
TRACTION_MIN_SCALE = 0.05

# --- Anti-tip ---
ANTI_TIP_BALANCE_ACCEL_REF = 25.0
ANTI_TIP_PITCH_DAMP_GAIN = 0.18
ANTI_TIP_PITCH_RESTORE_GAIN = 0.55
ANTI_TIP_RISK_BOOST_GAIN = 0.60
ANTI_TIP_MAX_SETPOINT_BIAS_RAD = float(np.deg2rad(8.0))

# --- Predictive longitudinal stance shift ---
STANCE_SHIFT_MAX_LEG_X_M = 0.25
STANCE_SHIFT_CMD_SPEED_MAX_MPS = 3.2
STANCE_SHIFT_SPEED_ERROR_TO_ACCEL_GAIN = 4.0
STANCE_SHIFT_ACCEL_MAX_MPS2 = 14.0
STANCE_SHIFT_TILT_TO_LEG_X_GAIN = 0.20
STANCE_SHIFT_FILTER_ALPHA = 0.55
STANCE_SHIFT_RISK_REDUCTION_GAIN = 0.70
STANCE_SHIFT_MIN_SCALE = 0.25
STANCE_SHIFT_IK_MIN_X_M = 1e-4

# --- Remote pitch/roll setpoint limits ---
MAX_REMOTE_PITCH_SETPOINT_RAD = float(np.deg2rad(12.0))
MAX_REMOTE_ROLL_SETPOINT_RAD = float(np.deg2rad(12.0))

# --- Bone prop ---
BONE_RESPAWN_COOLDOWN_STEPS = 20

# --- Voice command task ---
VOICE_PWM_PERIOD_STEPS = 10
VOICE_MOVE_STOP_TOL_M = 0.02
VOICE_MOVE_PULSE_NEAR_M = 0.10
VOICE_MOVE_PULSE_MID_M = 0.30
VOICE_MOVE_MAX_LATERAL_ERROR_M = 0.30
VOICE_ROT_STOP_TOL_RAD = float(np.deg2rad(2.0))
VOICE_ROT_PULSE_NEAR_RAD = float(np.deg2rad(8.0))
VOICE_ROT_PULSE_MID_RAD = float(np.deg2rad(24.0))
VOICE_TASK_TIP_PITCH_RAD = float(np.deg2rad(60.0))
VOICE_TASK_TIP_ROLL_RAD = float(np.deg2rad(60.0))
VOICE_MOVE_TIMEOUT_MIN_S = 4.0
VOICE_MOVE_TIMEOUT_PER_M_S = 8.0
VOICE_ROT_TIMEOUT_MIN_S = 4.0
VOICE_ROT_TIMEOUT_PER_RAD_S = 5.0
VOICE_PROGRESS_EMIT_INTERVAL_S = 0.1
VOICE_STUCK_CHECK_INTERVAL_S = 0.1
VOICE_STUCK_GRACE_S = 0.7
VOICE_STUCK_WINDOW_S = 2.0
VOICE_MOVE_STUCK_SPEED_MPS = 0.05
VOICE_ROT_STUCK_SPEED_RAD_S = float(np.deg2rad(3.0))

# --- Network defaults ---
DEFAULT_BACKEND_HOST = "0.0.0.0"
DEFAULT_BACKEND_PORT = 8000
DEFAULT_QUICK_TUNNEL_STARTUP_TIMEOUT_SEC = 20.0
DEFAULT_QUICK_TUNNEL_ATTEMPTS = 3
DEFAULT_QUICK_TUNNEL_PROTOCOL = "auto"
DEFAULT_QUICK_TUNNEL_EDGE_IP_VERSION = "auto"
DEFAULT_REMOTE_CONTROLLER_URL = "https://felipegalind0.github.io/gdog-remote"
DEFAULT_REMOTE_API_KEY_FILE = ".priv/api.md"
DEFAULT_REMOTE_API_KEY_QUERY_PARAM = "openai_key"
